/**
 * Self-contained browser ESM adapter for lz4-wasm.
 *
 * Why this exists: the `lz4-wasm` npm package ships the wasm-bindgen
 * "bundler" target. Its top-level `lz4_wasm.js` does
 *   `import * as wasm from "./lz4_wasm_bg.wasm";`
 * which only resolves under a bundler that treats `.wasm` as an asset.
 * Native browser ESM has no such resolver, and bare specifiers like
 * `'lz4-wasm'` don't resolve without an import map either. Rather than
 * pull in a bundler just for that, this file reimplements the bindings
 * inline and loads the .wasm with WebAssembly.instantiateStreaming.
 *
 * The bindings logic is a verbatim port of lz4-wasm's lz4_wasm_bg.js
 * (118 lines, generated by wasm-bindgen for crate version 0.9.2) with
 * the lone change that `wasm` is a module-scoped variable populated by
 * `ready()` rather than imported from the .wasm directly.
 *
 * API mirrors lz4-wasm-nodejs:
 *   await ready()                          one-time init; safe to await many times
 *   compress(Uint8Array) → Uint8Array      [u32 LE size][LZ4 raw block]
 *   decompress(Uint8Array) → Uint8Array    inverse of compress()
 */

let wasm = null;
let _initPromise = null;

let _u8 = null;
function _mem8() {
  if (_u8 === null || _u8.buffer !== wasm.memory.buffer) _u8 = new Uint8Array(wasm.memory.buffer);
  return _u8;
}

let _i32 = null;
function _memI32() {
  if (_i32 === null || _i32.buffer !== wasm.memory.buffer) _i32 = new Int32Array(wasm.memory.buffer);
  return _i32;
}

const _td = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true });
_td.decode();
function _decodeString(ptr, len) { return _td.decode(_mem8().subarray(ptr, ptr + len)); }

// Heap mirrors wasm-bindgen's small JsValue table. Used for error objects
// returned by decompress() when the input is malformed.
const _heap = new Array(32).fill(undefined);
_heap.push(undefined, null, true, false);
let _heapNext = _heap.length;
function _heapPush(obj) {
  if (_heapNext === _heap.length) _heap.push(_heap.length + 1);
  const idx = _heapNext;
  _heapNext = _heap[idx];
  _heap[idx] = obj;
  return idx;
}
function _heapTake(idx) {
  const v = _heap[idx];
  if (idx >= 36) { _heap[idx] = _heapNext; _heapNext = idx; }
  return v;
}

let _vecLen = 0;
function _passU8(buf, malloc) {
  const ptr = malloc(buf.length);
  _mem8().set(buf, ptr);
  _vecLen = buf.length;
  return ptr;
}
function _readU8(ptr, len) { return _mem8().subarray(ptr, ptr + len); }

// JS callback that the wasm module imports from the bindgen JS shim.
function __wbindgen_string_new(ptr, len) { return _heapPush(_decodeString(ptr, len)); }

export async function ready() {
  if (_initPromise) return _initPromise;
  const wasmUrl = new URL('./lz4_wasm_bg.wasm', import.meta.url);
  const importObject = {
    './lz4_wasm_bg.js': { __wbindgen_string_new },
  };
  _initPromise = (async () => {
    let instantiated;
    try {
      instantiated = await WebAssembly.instantiateStreaming(fetch(wasmUrl), importObject);
    } catch {
      // Some servers serve .wasm without `application/wasm`; fall back to
      // arrayBuffer + instantiate.
      const bytes = await (await fetch(wasmUrl)).arrayBuffer();
      instantiated = await WebAssembly.instantiate(bytes, importObject);
    }
    wasm = instantiated.instance.exports;
  })();
  return _initPromise;
}

export function compress(input) {
  if (!wasm) throw new Error('lz4-browser: await ready() before compress()');
  try {
    const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
    const ptr0 = _passU8(input, wasm.__wbindgen_malloc);
    wasm.compress(retptr, ptr0, _vecLen);
    const i32 = _memI32();
    const r0 = i32[retptr / 4 + 0];
    const r1 = i32[retptr / 4 + 1];
    const out = _readU8(r0, r1).slice();
    wasm.__wbindgen_free(r0, r1);
    return out;
  } finally {
    wasm.__wbindgen_add_to_stack_pointer(16);
  }
}

export function decompress(input) {
  if (!wasm) throw new Error('lz4-browser: await ready() before decompress()');
  try {
    const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
    const ptr0 = _passU8(input, wasm.__wbindgen_malloc);
    wasm.decompress(retptr, ptr0, _vecLen);
    const i32 = _memI32();
    const r0 = i32[retptr / 4 + 0];
    const r1 = i32[retptr / 4 + 1];
    const r2 = i32[retptr / 4 + 2];
    const r3 = i32[retptr / 4 + 3];
    if (r3) throw _heapTake(r2);
    const out = _readU8(r0, r1).slice();
    wasm.__wbindgen_free(r0, r1);
    return out;
  } finally {
    wasm.__wbindgen_add_to_stack_pointer(16);
  }
}
